---
version: 2
updates:
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: "docker"
  directory: "/foo"
  schedule:
    interval: "daily"
- package-ecosystem: "docker"
  directory: "/bar"
  schedule:
    interval: "daily"
